-- Fast simulation variant: BINS=16 instead of 7200
-- Same test logic, runs in milliseconds

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library std;
use std.env.all;

entity avg_tb_fast is
end entity avg_tb_fast;

architecture sim of avg_tb_fast is

    constant CLK_PERIOD : time    := 10 ns;
    constant BINS       : integer := 16;  -- reduced for simulation speed

    signal clk             : std_logic := '0';
    signal rst             : std_logic := '1';
    signal s_axis_tdata    : std_logic_vector(31 downto 0) := (others => '0');
    signal s_axis_tvalid   : std_logic := '0';
    signal s_axis_tready   : std_logic;
    signal s_axis_tlast    : std_logic := '0';
    signal m_axis_tdata    : std_logic_vector(31 downto 0);
    signal m_axis_tvalid   : std_logic;
    signal m_axis_tready   : std_logic := '1';
    signal m_axis_tlast    : std_logic;
    signal avg_n           : unsigned(3 downto 0) := (others => '0');
    signal rpm             : unsigned(15 downto 0) := to_unsigned(3000, 16);
    signal frame_count     : unsigned(31 downto 0);
    signal sim_done        : boolean := false;
    signal test_num        : integer := 0;

    -- Send one frame of BINS samples with uniform pressure
    procedure send_frame (
        constant pressure   : in integer;
        constant nbins      : in integer;
        signal   tdata      : out std_logic_vector(31 downto 0);
        signal   tvalid     : out std_logic;
        signal   tlast      : out std_logic;
        signal   tready     : in  std_logic;
        signal   clk        : in  std_logic
    ) is
    begin
        for bin in 0 to nbins - 1 loop
            tdata  <= std_logic_vector(to_unsigned(bin, 32));
            tvalid <= '1';
            tlast  <= '0';
            wait until rising_edge(clk) and tready = '1';
            tdata  <= std_logic_vector(
                        x"00" &
                        x"00" &
                        to_unsigned(pressure * 16, 16));
            if bin = nbins - 1 then tlast <= '1'; end if;
            wait until rising_edge(clk) and tready = '1';
        end loop;
        tvalid <= '0';
        tlast  <= '0';
        wait until rising_edge(clk);
    end procedure;

    procedure drain_words (
        constant n_words    : in  integer;
        signal   tvalid     : in  std_logic;
        signal   tready     : out std_logic;
        signal   clk        : in  std_logic
    ) is
    begin
        tready <= '1';
        for i in 0 to n_words - 1 loop
            wait until rising_edge(clk) and tvalid = '1';
        end loop;
    end procedure;

begin

    p_clk : process
    begin
        while not sim_done loop
            clk <= '0'; wait for CLK_PERIOD/2;
            clk <= '1'; wait for CLK_PERIOD/2;
        end loop;
        wait;
    end process;

    -- Instantiate avg with BINS=16 via generic
    -- NOTE: avg.vhd has BINS as a constant. For this fast TB we use a
    -- separate avg_fast entity generated by overriding the constant.
    -- Workaround: use configuration to remap, or just test avg.vhd directly
    -- with its native BINS=7200 but limit test scope.
    -- For now, instantiate avg directly and use short frames.
    dut : entity work.avg
        port map (
            clk          => clk, rst          => rst,
            s_axis_tdata => s_axis_tdata,  s_axis_tvalid => s_axis_tvalid,
            s_axis_tready=> s_axis_tready, s_axis_tlast  => s_axis_tlast,
            m_axis_tdata => m_axis_tdata,  m_axis_tvalid => m_axis_tvalid,
            m_axis_tready=> m_axis_tready, m_axis_tlast  => m_axis_tlast,
            avg_n        => avg_n,         rpm           => rpm,
            frame_count  => frame_count
        );

    p_stim : process
        variable data_v : std_logic_vector(31 downto 0);
    begin
        -- Reset
        rst <= '1'; wait for 5 * CLK_PERIOD;
        rst <= '0'; wait for 2 * CLK_PERIOD; wait for 1 ns;

        -- T1: Reset check
        report "TEST 1: Reset";
        assert m_axis_tvalid = '0'
            report "FAIL T1: tvalid should be low" severity failure;
        assert to_integer(frame_count) = 0
            report "FAIL T1: frame_count should be 0" severity failure;
        report "TEST 1: PASS";

        -- T2: Bypass
        report "TEST 2: Bypass (N=0)";
        avg_n <= to_unsigned(0, 4);
        m_axis_tready <= '1';
        s_axis_tdata  <= x"00000064";
        s_axis_tvalid <= '1';
        s_axis_tlast  <= '0';
        wait until rising_edge(clk) and s_axis_tready = '1'; wait for 1 ns;
        assert m_axis_tvalid = '1'
            report "FAIL T2: tvalid in bypass" severity failure;
        assert m_axis_tdata = x"00000064"
            report "FAIL T2: data mismatch in bypass" severity failure;
        s_axis_tdata  <= x"AABBCCDD";
        s_axis_tlast  <= '1';
        wait until rising_edge(clk) and s_axis_tready = '1'; wait for 1 ns;
        assert m_axis_tdata = x"AABBCCDD"
            report "FAIL T2: word1 mismatch in bypass" severity failure;
        assert m_axis_tlast = '1'
            report "FAIL T2: tlast in bypass" severity failure;
        s_axis_tvalid <= '0'; s_axis_tlast <= '0';
        wait for 5 * CLK_PERIOD;
        report "TEST 2: PASS";

        -- T3: N=1, 2 frames, pressure=100 per bin
        -- avg.vhd has BINS=7200 so we must send 7200 bins.
        -- We shorten to bins 0..15 and set the tlast early to simulate
        -- a reduced-bin engine cycle. avg.vhd uses bin address directly
        -- so bins 0..15 accumulate correctly; rest stay zero.
        -- We only check bins we sent.
        report "TEST 3: N=1 -- 2 frames, pressure=100, checking bin 0";
        test_num <= 3;
        avg_n <= to_unsigned(1, 4);
        rpm   <= to_unsigned(3000, 16);
        m_axis_tready <= '1';

        -- Frame 1: 16 bins then tlast (short frame)
        for bin in 0 to 15 loop
            s_axis_tdata  <= std_logic_vector(to_unsigned(bin, 32));
            s_axis_tvalid <= '1'; s_axis_tlast <= '0';
            wait until rising_edge(clk) and s_axis_tready = '1';
            s_axis_tdata <= x"00000640";  -- pressure=100 in [15:4]
            if bin = 15 then s_axis_tlast <= '1'; end if;
            wait until rising_edge(clk) and s_axis_tready = '1';
        end loop;
        s_axis_tvalid <= '0'; s_axis_tlast <= '0';
        wait for 5 * CLK_PERIOD;

        -- Frame 2: same
        for bin in 0 to 15 loop
            s_axis_tdata  <= std_logic_vector(to_unsigned(bin, 32));
            s_axis_tvalid <= '1'; s_axis_tlast <= '0';
            wait until rising_edge(clk) and s_axis_tready = '1';
            s_axis_tdata <= x"00000640";
            if bin = 15 then s_axis_tlast <= '1'; end if;
            wait until rising_edge(clk) and s_axis_tready = '1';
        end loop;
        s_axis_tvalid <= '0'; s_axis_tlast <= '0';

        -- Wait for output header
        wait until rising_edge(clk) and m_axis_tvalid = '1'; wait for 1 ns;
        assert unsigned(m_axis_tdata) = 3000
            report "FAIL T3: header rpm, got " &
                   integer'image(to_integer(unsigned(m_axis_tdata))) severity failure;
        wait until rising_edge(clk) and m_axis_tvalid = '1'; wait for 1 ns;
        assert unsigned(m_axis_tdata) = 1
            report "FAIL T3: header N" severity failure;

        -- Bin 0: expect 100
        wait until rising_edge(clk) and m_axis_tvalid = '1'; wait for 1 ns;
        assert to_integer(unsigned(m_axis_tdata)) = 100
            report "FAIL T3: bin 0, expected 100, got " &
                   integer'image(to_integer(unsigned(m_axis_tdata))) severity failure;
        report "TEST 3: bin 0 = 100 PASS";

        -- Drain remaining 7199 bins + wait for tlast
        wait until m_axis_tlast = '1' and m_axis_tvalid = '1';
        wait for 10 * CLK_PERIOD;
        assert to_integer(frame_count) = 1
            report "FAIL T3: frame_count should be 1" severity failure;
        report "TEST 3: PASS";

        -- T4: Back-pressure
        report "TEST 4: Back-pressure mid-frame";
        test_num <= 4;
        avg_n <= to_unsigned(1, 4);

        for bin in 0 to 15 loop
            s_axis_tdata  <= std_logic_vector(to_unsigned(bin, 32));
            s_axis_tvalid <= '1'; s_axis_tlast <= '0';
            wait until rising_edge(clk) and s_axis_tready = '1';
            s_axis_tdata <= x"00000320";  -- pressure=50
            if bin = 15 then s_axis_tlast <= '1'; end if;
            wait until rising_edge(clk) and s_axis_tready = '1';
        end loop;
        s_axis_tvalid <= '0'; s_axis_tlast <= '0';
        for bin in 0 to 15 loop
            s_axis_tdata  <= std_logic_vector(to_unsigned(bin, 32));
            s_axis_tvalid <= '1'; s_axis_tlast <= '0';
            wait until rising_edge(clk) and s_axis_tready = '1';
            s_axis_tdata <= x"00000320";
            if bin = 15 then s_axis_tlast <= '1'; end if;
            wait until rising_edge(clk) and s_axis_tready = '1';
        end loop;
        s_axis_tvalid <= '0'; s_axis_tlast <= '0';

        -- Wait for output to start, receive rpm header
        m_axis_tready <= '1';
        wait until rising_edge(clk) and m_axis_tvalid = '1'; -- rpm
        wait until rising_edge(clk) and m_axis_tvalid = '1'; -- N
        -- Receive bin 0, then assert back-pressure
        wait until rising_edge(clk) and m_axis_tvalid = '1';
        data_v := m_axis_tdata;
        m_axis_tready <= '0';
        wait for 20 * CLK_PERIOD; wait for 1 ns;
        assert m_axis_tvalid = '1'
            report "FAIL T4: tvalid dropped under back-pressure" severity failure;
        assert m_axis_tdata = data_v
            report "FAIL T4: data changed under back-pressure" severity failure;
        m_axis_tready <= '1';
        wait until m_axis_tlast = '1' and m_axis_tvalid = '1';
        wait for 10 * CLK_PERIOD;
        report "TEST 4: PASS";

        -- Done
        report "========================================";
        report "All avg fast tests PASS";
        report "========================================";
        sim_done <= true;
        std.env.stop;
        wait;
    end process p_stim;

end architecture sim;
